version: "3.7"

services:
  postgresDb:
    image: postgres:9.6.21-alpine
    container_name: postgres_db
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1'
        ]
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - 'impact_postgres:/var/lib/postgres/data'
    networks:
      - impact
    restart: always
  impact_api:
    build: .
    container_name: impact_api
    environment:
      NODE_ENV: development
    ports:
      - 4004:4004
    env_file:
      - .env
    links:
      - postgresDb
    depends_on:
      - postgresDb
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - impact
    restart: always
    command: npm run start:dev
networks:
  impact:
    driver: bridge
volumes:
  impact_postgres:
    driver: local
